/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__dummy
#define __PYX_HAVE__dummy


#ifndef __PYX_HAVE_API__dummy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) dummy(void *);
__PYX_EXTERN_C DL_IMPORT(int) init_clips6_dummy(void *);

#endif /* !__PYX_HAVE_API__dummy */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdummy(void);
#else
PyMODINIT_FUNC PyInit_dummy(void);
#endif

#endif /* !__PYX_HAVE__dummy */
