/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__clips6_cmd
#define __PYX_HAVE__clips6_cmd


#ifndef __PYX_HAVE_API__clips6_cmd

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) clips6_unload(void);
__PYX_EXTERN_C DL_IMPORT(void) EnvUserFunctions(void *);
__PYX_EXTERN_C DL_IMPORT(void) UserFunctions(void *);
__PYX_EXTERN_C DL_IMPORT(PyObject) *clips6_load_module(void *, char *);
__PYX_EXTERN_C DL_IMPORT(void) clips6_bufrouters_unload(void);
__PYX_EXTERN_C DL_IMPORT(int) FindCLP6IO(void *, char const *);
__PYX_EXTERN_C DL_IMPORT(int) ExitCLP6IO(void *, int);
__PYX_EXTERN_C DL_IMPORT(int) PrintCLP6IO(void *, char const *, char const *);
__PYX_EXTERN_C DL_IMPORT(int) GetcCLP6IO(void *, char const *);
__PYX_EXTERN_C DL_IMPORT(int) UngetcCLP6IO(void *, int, char const *);

#endif /* !__PYX_HAVE_API__clips6_cmd */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initclips6_cmd(void);
#else
PyMODINIT_FUNC PyInit_clips6_cmd(void);
#endif

#endif /* !__PYX_HAVE__clips6_cmd */
